### ISSUE TITLE
Fix rows skipped on upload excel file

### ISSUE THREAD

**Issue by ImaneChafi** [DDMAL/mei-mapping-tool#128]

**Comment by ImaneChafi** [comment]
The xlsx npm library used here skips row if they are blank : `https://github.com/SheetJS/js-xlsx/issues/139
The rows that didn't have a name were uploaded because there were multiple pictures on one row that couldn't be renamed to the same name. I'll need to change that part of the application.

**Comment by fujinaga** [comment]
Low priority, but it would be great if we can have more that one image per row.

On Aug 21, 2019, at 04:12, ImaneChafi <notifications@github.com<mailto:notifications@github.com>> wrote:


The xlsx npm library used here skips row if they are blank : `SheetJS/js-xlsx#139<https://github.com/SheetJS/js-xlsx/issues/139>
The rows that didn't have a name were uploaded because there were multiple pictures on one row that couldn't be renamed to the same name. I'll need to change that part of the application.

**Comment by ImaneChafi** [comment]
Perfect I'll work on that after the images are linked to the right column. The file that has the information between the id of the image and the media folder containing the images is  drawing1.xml.rels and the file that has the information about the row number and the images id is drawing1.xml. I'm using the two to link the right neumes with the right images.

**Comment by ImaneChafi** [comment]
The images are now being shown in the right order when uploaded, and linked to the right neume depending on the row and the id of the image taken from the xml file : https://github.com/DDMAL/mei-mapping-tool/commit/62c9005a21e2bcd337492111ea3c8ef7d24e31fd
I tried it out on 2 neumes, and I still need to do more testing for multiple neumes and different excel files.

**Comment by vigliensoni** [comment]
Shall I try it or do you want to do more testing first?

**Comment by ImaneChafi** [comment]
I can show you 2 neumes downloaded but I still haven't tried with multiple neumes so I'm going to test some more with multiple neumes to see if the logic still stands.

**Comment by ImaneChafi** [comment]
The upload now works for multiple neumes and they are in order, depending on their row number and the id of the image! I'm working on adding multiple images per row, but the upload works if there is one image per row, and it skips empty rows.
